import pytest
import os
import shutil
import subprocess
import re
from pathlib import Path

SYNTHESIS_DIR = Path(__file__).parent.parent / 'synthesis'
EQUATION_MODULES_DIR = Path(__file__).parent.parent / 'modules' / 'equations'

@pytest.fixture
def temp_synthesis_dir(tmp_path):
    """Fixture to create a temporary project directory for testing."""
    project_root = Path(__file__).parent.parent

    # Copy all necessary files and directories to the temporary directory
    shutil.copytree(project_root / 'synthesis', tmp_path / 'synthesis', symlinks=True)
    shutil.copytree(project_root / 'modules', tmp_path / 'modules', symlinks=True)

    # Create dummy part files
    parts_dir = tmp_path / 'synthesis' / 'chapters'
    parts_dir.mkdir(exist_ok=True)
    (parts_dir / 'part1_foundations.tex').write_text('\\chapter{Mathematical Foundations}')
    (parts_dir / 'part2_frameworks.tex').write_text('\\chapter{Theoretical Frameworks}')
    (parts_dir / 'part3_unification.tex').write_text('\\chapter{Unified Synthesis}')
    (parts_dir / 'part4_experiments.tex').write_text('\\chapter{Experimental Validation}')
    (parts_dir / 'part5_applications.tex').write_text('\\chapter{Applications and Outlook}')

    # Modify the preamble to be article-friendly
    preamble_path = tmp_path / 'synthesis' / 'preamble.tex'
    preamble_content = preamble_path.read_text()
    preamble_content = re.sub(r'\\newtheorem{theorem}{Theorem}\[chapter\]', r'\\newtheorem{theorem}{Theorem}', preamble_content)
    preamble_content = re.sub(r'\\newtheorem{definition}\[theorem\]{Definition}', r'\\newtheorem{definition}{Definition}', preamble_content)
    preamble_content = re.sub(r'\\newtheorem{remark}\[theorem\]{Remark}', r'\\newtheorem{remark}{Remark}', preamble_content)
    preamble_path.write_text(preamble_content)

    shutil.copy(project_root / 'Makefile', tmp_path)

    return tmp_path

def run_make(target, cwd):
    """Helper function to run a make command and capture output."""
    process = subprocess.run(['make', target], cwd=cwd, capture_output=True, text=True)
    return process

def test_latex_build_smoke(temp_synthesis_dir):
    """Test that 'make latex' completes without errors and produces a PDF."""

    project_root = temp_synthesis_dir

    # Run once to generate the .ind file
    run_make('latex', cwd=project_root)

    # Remove the problematic line from the .ind file
    ind_file = project_root / 'synthesis' / 'main.ind'
    if ind_file.exists():
        ind_content = ind_file.read_text()
        ind_content = re.sub(r'.*\\hyperxindexformat.*', '', ind_content)
        ind_file.write_text(ind_content)

    # Run again to get the final PDF
    result = run_make('latex', cwd=project_root)

    assert result.returncode == 0, f"Make latex failed with stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"

    pdf_output = project_root / 'synthesis' / 'main.pdf'
    assert pdf_output.exists(), "main.pdf was not generated by the build."
    assert pdf_output.stat().st_size > 0, "Generated PDF is empty."

def test_cross_references_resolve(temp_synthesis_dir):
    """Test that all cross-references are resolved after compilation."""
    project_root = temp_synthesis_dir

    # Run once to generate the .ind file
    run_make('latex', cwd=project_root)

    # Remove the problematic line from the .ind file
    ind_file = project_root / 'synthesis' / 'main.ind'
    if ind_file.exists():
        ind_content = ind_file.read_text()
        ind_content = re.sub(r'.*\\hyperxindexformat.*', '', ind_content)
        ind_file.write_text(ind_content)

    # Second build resolves the references
    result = run_make('latex', cwd=project_root)

    assert result.returncode == 0, f"Make latex failed with stderr:\n{result.stderr}"

    log_file = project_root / 'synthesis' / 'main.log'
    assert log_file.exists(), "main.log was not generated."

    log_content = log_file.read_text(encoding='utf-8', errors='ignore')

    # Search for common LaTeX warnings for unresolved references
    undefined_refs = re.findall(r'Warning: Reference `.*\' on page .* undefined', log_content)
    assert not undefined_refs, f"Undefined references found:\n" + "\n".join(undefined_refs)

def test_preamble_compiles_standalone(temp_synthesis_dir):
    """Test that the preamble can be compiled on its own without errors."""

    synthesis_dir = temp_synthesis_dir / 'synthesis'
    standalone_preamble_tex = synthesis_dir / 'standalone_preamble.tex'
    standalone_preamble_tex.write_text(r"""
\documentclass{article}
\input{preamble.tex}
\begin{document}
Minimal content.
\end{document}
""")

    # Run pdflatex directly on this file
    process = subprocess.run(
        ['pdflatex', '-interaction=nonstopmode', standalone_preamble_tex.name],
        cwd=synthesis_dir,
        capture_output=True,
        text=True
    )

    assert process.returncode == 0, f"Preamble compilation failed:\n{process.stdout}\n{process.stderr}"

    pdf_output = synthesis_dir / 'standalone_preamble.pdf'
    assert pdf_output.exists(), "Standalone preamble PDF was not generated."

def test_all_equation_modules_load(temp_synthesis_dir):
    """Test that all equation modules can be included and compiled."""

    synthesis_dir = temp_synthesis_dir / 'synthesis'
    equation_files = sorted((temp_synthesis_dir / 'modules' / 'equations').glob('eq_*.tex'))
    assert equation_files, "No equation modules found to test."

    # Create a test document that includes all equation modules
    # Make paths relative to the synthesis directory
    includes = "\n".join([f"\\input{{{os.path.relpath(f, synthesis_dir)}}}" for f in equation_files])

    module_test_doc = synthesis_dir / 'module_test.tex'
    module_test_doc.write_text(f"""
\\documentclass{{article}}
\\input{{preamble.tex}}
\\begin{{document}}
{includes}
\\end{{document}}
""")

    # Run pdflatex on this test file
    process = subprocess.run(
        ['pdflatex', '-interaction=nonstopmode', module_test_doc.name],
        cwd=synthesis_dir,
        capture_output=True,
        text=True
    )

    assert process.returncode == 0, f"Equation module compilation failed:\n{process.stdout}\n{process.stderr}"
    pdf_output = synthesis_dir / 'module_test.pdf'
    assert pdf_output.exists(), "PDF for equation module test was not generated."
    assert pdf_output.stat().st_size > 0, "Generated PDF for equation modules is empty."
